var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/documents/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t9onzw._.js")
R.c("server/chunks/ssr/node_modules_next_0oc5r9b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0w7odac._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02rypge._.js")
R.c("server/chunks/ssr/_0hz55tm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_documents_new_page_actions_06x8a_o.js")
R.m(16514)
module.exports=R.m(16514).exports
