var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/users/[id]/events/export/route.js")
R.c("server/chunks/[externals]__0l8ei7u._.js")
R.c("server/chunks/_14ra4y5._.js")
R.c("server/chunks/_0prvgb4._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_0p9s6i4._.js")
R.c("server/chunks/[root-of-the-server]__0l3yhx4._.js")
R.c("server/chunks/lib_pocketbase_ts_16pu7lb._.js")
R.c("server/chunks/1oeh_server_app_api_admin_users_[id]_events_export_route_actions_11hkjl7.js")
R.m(65833)
module.exports=R.m(65833).exports
