// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/account" | "/dashboard/activity-log" | "/dashboard/customers" | "/dashboard/customers/[id]" | "/dashboard/customers/new" | "/dashboard/documents/new" | "/dashboard/reports" | "/dashboard/settings" | "/dashboard/users" | "/register"
type AppRouteHandlerRoutes = "/api/account/authenticator/disable" | "/api/account/authenticator/setup" | "/api/account/authenticator/verify" | "/api/account/profile" | "/api/admin/activity-log" | "/api/admin/users" | "/api/admin/users/[id]/events" | "/api/admin/users/[id]/events/export" | "/api/admin/users/[id]/password-reset" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/customers" | "/api/customers/[id]" | "/api/customers/[id]/transactions" | "/api/customers/export" | "/api/documents"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/account/authenticator/disable": {}
  "/api/account/authenticator/setup": {}
  "/api/account/authenticator/verify": {}
  "/api/account/profile": {}
  "/api/admin/activity-log": {}
  "/api/admin/users": {}
  "/api/admin/users/[id]/events": { "id": string; }
  "/api/admin/users/[id]/events/export": { "id": string; }
  "/api/admin/users/[id]/password-reset": { "id": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/customers": {}
  "/api/customers/[id]": { "id": string; }
  "/api/customers/[id]/transactions": { "id": string; }
  "/api/customers/export": {}
  "/api/documents": {}
  "/dashboard": {}
  "/dashboard/account": {}
  "/dashboard/activity-log": {}
  "/dashboard/customers": {}
  "/dashboard/customers/[id]": { "id": string; }
  "/dashboard/customers/new": {}
  "/dashboard/documents/new": {}
  "/dashboard/reports": {}
  "/dashboard/settings": {}
  "/dashboard/users": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
