var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/customers/export/route.js")
R.c("server/chunks/[root-of-the-server]__1bhumt7._.js")
R.c("server/chunks/_14ra4y5._.js")
R.c("server/chunks/lib_pocketbase_ts_16pu7lb._.js")
R.c("server/chunks/[root-of-the-server]__0l3yhx4._.js")
R.c("server/chunks/[root-of-the-server]__14v3ph-._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_0p9s6i4._.js")
R.c("server/chunks/_next-internal_server_app_api_customers_export_route_actions_18p9w29.js")
R.m(78990)
module.exports=R.m(78990).exports
