var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/activity-log/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wvjfau._.js")
R.c("server/chunks/ssr/node_modules_next_0oc5r9b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0w7odac._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02rypge._.js")
R.c("server/chunks/ssr/_0hz55tm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_activity-log_page_actions_0pcuu_h.js")
R.m(65879)
module.exports=R.m(65879).exports
